<a href="https://colab.research.google.com/github/jngadiub/ML_course_Pavia_23/blob/main/python_advance/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

Based on [W3Schools tutorial](https://www.w3schools.com/python/numpy/default.asp) and [Wuhan DL Lab](https://github.com/farakiko/wuhan_DL_labs/blob/master/general/Intro_Numpy.ipynb).

[**NumPy**](https://github.com/numpy/numpy) is short for "*Numerical Python*". It is a Python library used for working with arrays and it is used in almost all numerical computation using Python. It has functions for working in domain of linear algebra, fourier transform, and matrices. It was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

**Why Use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. Arrays are very frequently used in data science, where speed and resources are very important.

NumPy provides high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance are very good.

The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with arrays very easy.

**Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called *locality of reference* in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

**Useful Links**

* http://jrjohansson.github.io/numericalpython.html
* http://numpy.org
* https://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial


### Creating Arrays

We can create a NumPy `ndarray` object by using the `array()` function:

In [1]:
#To use NumPy we need to import the numpy module first:
import numpy as np

In [2]:
#Create and inspect the array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


There are a number of ways to initialize new NumPy arrays, for example from:

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.
* reading data from files



A dimension in arrays is one level of array depth in nested arrays, i.e. arrays that have arrays as their elements:

**0-D array**

In [3]:
arr = np.array(42)
print(arr)

42


**1-D array**

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


**2-D array**

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**3-D array**

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


NumPy arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have:

In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type?

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


### Fast Array Generation

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in numpy that generates arrays of different forms. Some of the more common are:

**arange**


In [8]:
arr = np.arange(0, 10, 1) # arguments: start, stop, step
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr = np.arange(-1, 1, 0.1)
print(arr)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


**linspace and logspace**

In [10]:
arr = np.linspace(0, 10, 25)
print(arr)

[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]


In [11]:
arr = np.logspace(0, 10, 10, base=np.e)
print(arr)

[1.00000000e+00 3.03773178e+00 9.22781435e+00 2.80316249e+01
 8.51525577e+01 2.58670631e+02 7.85771994e+02 2.38696456e+03
 7.25095809e+03 2.20264658e+04]


**mgrid**

In [12]:
x, y = np.mgrid[0:5, 0:5]

In [13]:
print(x)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [14]:
print(y)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**random data**

In [15]:
# uniform random numbers in [0,1]
arr = np.random.rand(5,5)
print(arr)

[[0.50262705 0.39491852 0.46821491 0.16807854 0.90628389]
 [0.64335462 0.45660272 0.55706581 0.68915681 0.19930885]
 [0.26021072 0.80934872 0.16918109 0.9624085  0.70456623]
 [0.30366077 0.81836853 0.53481993 0.322703   0.81247508]
 [0.34286415 0.82165287 0.0670651  0.84252378 0.26926061]]


In [16]:
# standard normal distributed random numbers
arr = np.random.randn(5,5)
print(arr)

[[-0.25580473  1.03886808 -1.4030536   0.44570764 -1.36959967]
 [-0.08328944 -1.35117971 -2.01630714 -2.05559713 -0.1259068 ]
 [ 1.15088921  0.14074604  0.04457984  0.01877679 -0.62683257]
 [ 1.18318947 -0.45498179  0.27117358  0.46894791  1.80025694]
 [ 1.62198569 -0.76711864 -1.13866407 -0.68431074 -2.09920541]]


**diag**

In [17]:
# a diagonal matrix
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


**zeros and ones**

In [18]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Access Array Elements

Array indexing is the same as accessing elements in python arrays:

In [20]:
arr = np.array([1, 2, 3, 4])

print(arr[0]) 
print(arr[1])
print(arr[2] + arr[3])  

1
2
7


To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column:

In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('2nd element on 1st row: ', arr[0, 1]) 
print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
5th element on 2nd row:  10


To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element:

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) 

6


In the example above, the first number represents the first dimension, which contains two arrays:

`[[1, 2, 3], [4, 5, 6]]` and `[[7, 8, 9], [10, 11, 12]]`

Since we selected `0`, we are left with the first array: `[[1, 2, 3], [4, 5, 6]]`.

The second number represents the second dimension, which also contains two arrays:

`[1, 2, 3]` and `[4, 5, 6]`

Since we selected `1`, we are left with the second array: `[4, 5, 6]`.

The third number represents the third dimension, which contains three values: `4`, `5`, and `6`. Since we selected `2`, we end up with the third value: `6`.

### Array Sclicing

Slicing for NumPy arrays is similar to python arrays (see notebook [`python_intro_part1.ipynb`](https://github.com/jngadiub/ML_course_Pavia_23/blob/main/python_basics/python_intro_part1.ipynb)). Let's see here a few more features. 

The `step` value can be used to determine the step of the slicing. The example below returns every other element from index `1` to index `5`:

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) 

[2 4]


*Exercise 1: print every other element of the entire array.*

*Exercise 2: create a 2D array and from the second element of the first dimension, slice elements from index 1 to index 4.*

*Exercise 3: create a 2D array and from both elements of the first dimension, return the element with index 2.*

*Exercise 4: create a 2D array and from the both elements of the first dimension, slice elements from index 1 to index 4.*

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
two_d_array = np.random.randint(0,10,(5,5))

print(two_d_array)

[[8 8 8 2 4]
 [4 3 6 9 0]
 [2 5 2 5 4]
 [4 5 9 5 0]
 [5 2 2 2 8]]


In [49]:
ex_01 = arr[::2]
print(ex_01)

ex_02 = two_d_array[0][1:4]
print(ex_02)

ex_03 = two_d_array[0][2]
print(ex_03)

ex_04 = two_d_array[0][1:4]
print(ex_04)

[1 3 5 7]
[8 8 2]
8
[8 8 2]


### Data Types

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:


In [24]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype) 

int32


We get an error if we try to assign a value of the wrong type to an element in a numpy array:


In [25]:
arr[0] = "hello"   # error on purpose


ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument:

**Example 1**


In [ ]:
arr = np.array([1, 2, 3, 4], dtype=complex)
print(arr)
print(arr.dtype) 

**Example 2**

In [ ]:
arr = np.array([0, 2, 3, 4], dtype=bool)
print(arr)
print(arr.dtype)

Common type that can be used with dtype are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float32`, `complex128`.


In [ ]:
arr = np.array([0, 2, 3, 4], dtype='float32')
print(arr)
print(arr.dtype)

A way to change the data type of an existing array, is to make a copy of the array with the `astype()` method. This function creates a copy of the array, and allows you to specify the data type as a parameter:



In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('int32')

print(newarr)
print(newarr.dtype)

### Array Copy

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (techincal term: *pass by reference*).


In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)

In [ ]:
# now B is referring to the same array data as A 
B = A 

In [ ]:
# changing B affects A
B[0,0] = 10
print(B)

In [ ]:
print(A)

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "*deep copy*" using the function `copy`:

In [ ]:
B = np.copy(A)
# now, if we modify B, A is not affected
B[0,0] = -5
print(B)

In [ ]:
print(A)

### Array Shape

The shape of an array is the number of elements in each dimension. NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements:

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

The example above returns `(2, 4)`, which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

*Exercise: create an array with 5 dimensions using `ndmin` and a vector with four elements and verify that last dimension has value 4.*

Reshaping means changing the shape of an array. By reshaping we can add or remove dimensions or change number of elements in each dimension.

**Reshape From 1-D to 2-D**

In [59]:
#Exercise

ex_array = np.random.randint(0,10,(5,5,5,5,5))
ex_vec = np.random.randint(0,10,4)
ex_vec

for i in range(ex_array.ndim):
    print(i)

0
1
2
3
4


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping:",arr.shape)

arr = arr.reshape(4, 3)
print("After reshaping",arr.shape)
print(arr)

**Reshape From 1-D to 3-D**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping:",arr.shape)

arr = arr.reshape(2, 3, 2)
print("After reshaping",arr.shape)
print(arr)

**Can We Reshape Into any Shape?**
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into a matrix of 2 rows and 4 columns but we cannot reshape it into a matrix of 3 rows and 3 columns as that would require 3x3 = 9 elements, while we have only 8 in the original 1D array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = arr.reshape(3, 3) #error on purpose

You are allowed to have one "unknown" dimension. Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method. Pass `-1` as the value, and NumPy will calculate this number for you:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Before reshaping:",arr.shape)

arr = arr.reshape(2, 2, -1)
print("After reshaping",arr.shape)
print(arr)

Flattening array means converting a multidimensional array into a 1D array. We can use the `flatten` method to do this:

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print("Before flattening:",arr.shape)

arr = arr.flatten()
print("After flattening:",arr.shape)

**Note**: both the `reshape` and `flatten` functions create a deep copy of the data.


### Iterating Arrays

Iterating means going through elements one by one. As we deal with multi-dimensional arrays in numpy, we can do this using basic `for` loop of python.

If we iterate on a 1-D array it will go through each element one by one:



In [ ]:
arr = np.array([1, 2, 3])
for x in arr: print(x) 

In a 2-D array it will go through all the rows:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr: print(x) 

In a 3-D array it will go through all the 2-D arrays:

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr: print(x) 

To return the actual elements, the scalars, we have to iterate the arrays in each dimension:

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y: print(z) 

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality. The function `nditer()` is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples. 

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr): print(x) 

We can also iterate using a fix step size:

In [ ]:
#Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]): print(x) 

Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases:

In [ ]:
#1D array
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr): print(idx, x)

In [ ]:
#2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr): print(idx, x)

### Joining Arrays

Joining means putting contents of two or more arrays in a single array. In NumPy we join arrays by axes. We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as `0`.

In [ ]:
#Example 1
arr1 = np.array([1, 2, 3])
print("arr1 shape:",arr1.shape)
arr2 = np.array([4, 5, 6])
print("arr2 shape:",arr2.shape)

arr = np.concatenate((arr1, arr2))
print("arr shape:",arr.shape)
print(arr) 

In [ ]:
#Example 2
arr1 = np.array([[1, 2], [3, 4]])
print("arr1 shape:",arr1.shape)
print(arr1)
arr2 = np.array([[5, 6], [7, 8]])
print("arr2 shape:",arr2.shape)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=1)
print("arr shape:",arr.shape)
print(arr)

In [ ]:
#Example 3
arr1 = np.array([[1, 2], [3, 4]])
print("arr1 shape:",arr1.shape)
print(arr1)
arr2 = np.array([[5, 6], [7, 8]])
print("arr2 shape:",arr2.shape)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=0)
print("arr shape:",arr.shape)
print(arr)

*Exercise: concatenate two 3D arrays on the the third dimension and return the final shape.*

In [65]:
threed_arr_1 = np.random.randint(0,10,(3,3,3))
threed_arr_2 = np.random.randint(0,10,(3,3,3))

np.concatenate((threed_arr_1,threed_arr_1), axis=2).shape


(3, 3, 6)

Stacking is same as concatenation, the only difference is that stacking is done along a new axis. We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking. We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
arr1 = np.array([1, 2, 3])
print("arr1 shape:",arr1.shape)
arr2 = np.array([4, 5, 6])
print("arr2 shape:",arr2.shape)

arr = np.stack((arr1, arr2), axis=1)
print("arr shape:",arr.shape)
print(arr)

NumPy provides the helper functions `hstack()`, `vstack()`, and `dstack()` to stack along rows, columns, and height (or depth), respectively:



In [ ]:
#Stack along rows
arr1 = np.array([1, 2, 3])
print("arr1 shape:",arr1.shape)
arr2 = np.array([4, 5, 6])
print("arr2 shape:",arr2.shape)

arr = np.hstack((arr1, arr2))
print("arr shape:",arr.shape)
print(arr)

In [ ]:
#Stack along columns
arr1 = np.array([1, 2, 3])
print("arr1 shape:",arr1.shape)
arr2 = np.array([4, 5, 6])
print("arr2 shape:",arr2.shape)

arr = np.vstack((arr1, arr2))
print("arr shape:",arr.shape)
print(arr) 

In [ ]:
#Stack along depth
arr1 = np.array([1, 2, 3])
print("arr1 shape:",arr1.shape)
arr2 = np.array([4, 5, 6])
print("arr2 shape:",arr2.shape)

arr = np.dstack((arr1, arr2))
print("arr shape:",arr.shape)
print(arr) 

With `newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:


In [ ]:
v = np.array([1,2,3])
print(v)
print(v.shape)

In [ ]:
# make a column matrix of the vector v
a = v[:, np.newaxis]
print(a)
print(a.shape)

In [ ]:
# make a row matrix of the vector v
a = v[np.newaxis,:]
print(a)
print(a.shape)

Other methods to join and reshape arrays are `repeat` and `tile`:

In [ ]:
# repeat each element 3 times
np.repeat([1,2,5], 3)

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
# repeat each element from a 3 times
np.repeat(a, 3)

In [ ]:
# tile the matrix a 3 times 
np.tile(a, 3)

### Array Search

You can search an array for a certain value, and return the indexes that get a match using the `where()` method:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x) 

The example above will return a tuple: `(array([3, 5, 6],)`. This means that the value 4 is present at index `3`, `5`, and `6`.

*Exercise 1: create a NumPy array of integers and find the indexes where the values are even.*

*Exercise 2: create a NumPy array of integers and find the indexes where the values are odd.*

In [73]:
ex_01_array = np.random.randint(0,10,10)
print(ex_01_array)
print(np.where(ex_01_array%2==0))
print(np.where(ex_01_array%2==1))

[2 6 1 1 1 1 9 1 6 2]
(array([0, 1, 8, 9], dtype=int64),)
(array([2, 3, 4, 5, 6, 7], dtype=int64),)


### Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called *filtering*. In NumPy, you filter an array using a boolean index list.

If the value at an index is `True` that element is contained in the filtered array, if the value at that index is `False` that element is excluded from the filtered array.

In [ ]:
arr = np.array([41, 42, 43, 44])
print("Before filtering:")
print(arr)

x = [True, False, True, False]

arr = arr[x]
print("After filtering:")
print(arr) 

In the example above we hard-coded the `True` and `False` values, but the common use is to create a filter array based on conditions.

For example, we can create a filter array that will return only values higher than `42`:

In [74]:
arr = np.array([41, 42, 43, 44])
print("Before filtering:")
print(arr)

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

arr = arr[filter_arr]

print("Filter:")
print(filter_arr)
print("After filtering:")
print(arr) 

Before filtering:
[41 42 43 44]
Filter:
[False, False, True, True]
After filtering:
[43 44]


The above examples are quite a common task in NumPy and NumPy provides a nice way to tackle it. We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to:

In [75]:
arr = np.array([41, 42, 43, 44])
print("Before filtering:")
print(arr)

filter_arr = arr > 42
print("Filter:")
print(filter_arr)

arr = arr[filter_arr]
print("After filtering:")
print(arr)

Before filtering:
[41 42 43 44]
Filter:
[False False  True  True]
After filtering:
[43 44]


*Exercise: create a filter array that will return only even elements from the original array.*

In [78]:
ex_01_array = np.random.randint(0,10,10)
print(ex_01_array)
arr = ex_01_array[ex_01_array%2==0]
print(arr)

[4 8 9 7 4 2 8 5 8 9]
[4 8 4 2 8 8]


### Linear Algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.


**Scalar-array operations**

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.


In [ ]:
v1 = np.arange(0, 5)
print(v1)

In [ ]:
arr = v1 * 2
print(arr)

In [ ]:
arr = v1 + 2
print(arr)

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(A)
print(A*2)
print(A+2)

**Element-wise array-array operations**

When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations:


In [ ]:
print(A * A) # element-wise multiplication

**Broadcasting**

(see https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:


In [ ]:
A.shape, v1.shape

In [ ]:
A * v1

**Matrix algebra**

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

In [ ]:
A = np.random.randint(5, size=(2,2))
print(A)
print(np.dot(A, A))

In [ ]:
v1 = np.random.randint(5, size=(2,))
print(v1)
print(np.dot(A, v1))

In [ ]:
np.dot(v1, v1)

Alternatively, we can cast the array objects to the type matrix. This changes the behavior of the standard arithmetic operators `+`, `-`, `*` to use matrix algebra.


In [ ]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [ ]:
v

In [ ]:
M * M

In [ ]:
M * v

In [ ]:
# inner product
v.T * v

In [ ]:
# with matrix objects, standard matrix algebra applies
v + M*v

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [ ]:
v = np.matrix([1,2,3,4,5,6]).T
np.shape(M), np.shape(v)

In [ ]:
M * v #error on purpose

**Array/Matrix transformations**

Above we have used the `.T` to transpose the matrix object `v`. We could also have used the transpose function to accomplish the same thing.

Other mathematical functions that transforms matrix objects are:

In [ ]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

In [ ]:
np.conjugate(C)

In [ ]:
#Hermitian conjugate: transpose + conjugate
C.H

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag` methods:

In [ ]:
np.real(C) # same as: C.real

In [ ]:
np.imag(C) # same as: C.imag

Or we can extract the complex argument and absolute value:

In [ ]:
np.angle(C+1)

In [ ]:
np.abs(C)

**Matrix computations**

In [ ]:
#inverse
np.linalg.inv(C) # equivalent to C.I 

In [ ]:
C.I * C

In [ ]:
#Determinant
np.linalg.det(C)

In [ ]:
np.linalg.det(C.I)

## Arrays I/O

**Comma-separated values (CSV)**

A very common file format for data files are the comma-separated values (CSV), or related format such as TSV (tab-separated values). To read data from such file into Numpy arrays we can use the `numpy.genfromtxt()` function. For example,


In [ ]:
#Fetch data file from githun
!curl https://raw.githubusercontent.com/jngadiub/ML_course_Pavia_23/main/python_advance/stockholm_td_adj.dat -o stockholm_td_adj.dat

#Look first 10 lines of file
!head stockholm_td_adj.dat

In [ ]:
data = np.genfromtxt('stockholm_td_adj.dat')
data.shape

In [ ]:
# we need this for plotting -- more on matlplotlib in next tutorial
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Now we plot the data
fig, ax = plt.subplots(figsize=(14,4))
ax.plot(data[:,0]+data[:,1]/12.0+data[:,2]/365, data[:,5])
ax.axis('tight')
ax.set_title('tempeatures in Stockholm')
ax.set_xlabel('year')
ax.set_ylabel('temperature (C)');

Using `numpy.savetxt()` we can store a Numpy array to a file in CSV format:


In [ ]:
arr = np.random.rand(3,3)
print(arr)

In [ ]:
np.savetxt("random-matrix.csv", arr)
!ls ./

In [ ]:
#Let's look at the file
!cat random-matrix.csv

In [ ]:
np.savetxt("random-matrix.csv", arr, fmt='%.5f') # fmt specifies the format
!cat random-matrix.csv

**Numpy's native file format**

Useful when storing and reading back NumPy array data. Use the functions `numpy.save()` and `numpy.load()`:


In [ ]:
arr = np.random.rand(3,3)
print(arr)

np.save("random-matrix.npy", arr)
!ls ./

In [ ]:
arr = np.load("random-matrix.npy")
print(arr)

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays.

For example, let's calculate some properties data from the Stockholm temperature dataset used above.


In [ ]:
# reminder, the tempeature dataset is stored in the data variable:
np.shape(data)

**mean**

In [ ]:
# the temperature data is in column 3
np.mean(data[:,3])

The daily mean temperature in Stockholm over the last 200 year so has been about 6.2 C.

**standard deviations and variance**

In [ ]:
np.std(data[:,3]), np.var(data[:,3])

**min and max**

In [ ]:
# lowest daily average temperature
data[:,3].min()

In [ ]:
# highest daily average temperature
data[:,3].max()

**sum, prod, and trace**

In [ ]:
d = np.arange(0, 10)
d

In [ ]:
# sum up all elements
np.sum(d)

In [ ]:
# product of all elements
np.prod(d+1)

In [ ]:
# cummulative sum
np.cumsum(d)

In [ ]:
# cummulative product
np.cumprod(d+1)

In [ ]:
# same as: diag(A).sum()
np.trace(A)

**Calculations with higher-dimensional data**

When functions such as `min`, `max`, etc., is applied to multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave:


In [ ]:
m = np.random.rand(3,3)
m

In [ ]:
# global max
m.max()

In [ ]:
# max in each column
m.max(axis=0)

In [ ]:
# max in each row
m.max(axis=1)

**Note:** Many other functions and methods in the array and matrix classes accept the same (optional) `axis` keyword argument.
